name: ML Model Architecture Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  model-architecture-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Enable pip caching
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: List installed packages
      run: |
        pip list
        
    - name: Check Python version and CUDA availability
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import torch; print(f'PyTorch {torch.__version__}')"
        python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"
        
    - name: Run Model Architecture Checks
      run: |
        python .github/scripts/check_model_architecture.py

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-